# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.


* 1) Indexing
    - 1.1) Indexing 1D array (Vectors)
    - 1.2) Indexing 2D array (Matrices)
    - 1.3) Fancy Indexing
* 2) Selection

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(30,40)

In [3]:
#Show
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

## 1) Indexing
The simplest way to pick one or some elements of an array looks very similar to python lists:

### 1.1) Indexing a 1D array (Vectors)

In [4]:
#Get a value at an index
arr[8]

38

In [5]:
#Get values in a range
arr[1:5]

array([31, 32, 33, 34])

In [6]:
#Get values in a range
arr[0:5]

array([30, 31, 32, 33, 34])

In [7]:
arr[:5]

array([30, 31, 32, 33, 34])

In [8]:
arr[3:]

array([33, 34, 35, 36, 37, 38, 39])

In [9]:
arr[3:7]

array([33, 34, 35, 36])

In [10]:
arr[3:7:2]

array([33, 35])

In [11]:
arr = np.arange(30,40)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [13]:
#Setting a value with index range (Broadcasting)
arr[2:5] = 100

#Show
arr

array([ 30,  31, 100, 100, 100,  35,  36,  37,  38,  39])

### 1.2) Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [14]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [16]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [17]:
# Getting individual element value
arr_2d[1, 0]

20

In [18]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [20]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [21]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[::-1,::]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [24]:
arr_2d[:,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [25]:
arr_2d[::-1,::-1]

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

### 1.3) Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [28]:
#Set up matrix
arr2d = np.random.randint(1, 100, (10,10))
arr2d

array([[81, 14, 15,  6, 18, 99, 32, 66, 58,  6],
       [97, 89, 58, 23, 20, 26, 91,  2, 63, 33],
       [91, 82, 27, 59, 48, 17, 89, 65, 65, 74],
       [98, 19, 59, 98, 90, 97, 72, 55, 77, 47],
       [ 1, 23, 80, 89, 33, 79, 92, 12,  2, 97],
       [23, 45, 41, 59, 48, 33, 84, 61, 85, 93],
       [11, 96, 47, 57, 95, 82, 70, 75, 22, 78],
       [ 1, 37,  7, 41, 89, 55, 97, 37, 74, 31],
       [70, 98, 88, 30, 62, 27, 41, 26, 21, 83],
       [67,  4, 17, 12,  8, 18, 78, 54, 73, 19]])

Fancy indexing allows the following

In [29]:
arr2d[[1,4,6,8]]

array([[97, 89, 58, 23, 20, 26, 91,  2, 63, 33],
       [ 1, 23, 80, 89, 33, 79, 92, 12,  2, 97],
       [11, 96, 47, 57, 95, 82, 70, 75, 22, 78],
       [70, 98, 88, 30, 62, 27, 41, 26, 21, 83]])

In [30]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[11, 96, 47, 57, 95, 82, 70, 75, 22, 78],
       [ 1, 23, 80, 89, 33, 79, 92, 12,  2, 97],
       [91, 82, 27, 59, 48, 17, 89, 65, 65, 74],
       [ 1, 37,  7, 41, 89, 55, 97, 37, 74, 31]])

In [31]:
arr2d[[1,4,6,8], 2:5]

array([[58, 23, 20],
       [80, 89, 33],
       [47, 57, 95],
       [88, 30, 62]])

## 2) Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [32]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [40]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True])

In [45]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [46]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[arr >= 5]

array([5, 6, 7, 8, 9])

In [34]:
x = 3
arr[arr > x]

array([4, 5, 6, 7, 8, 9])

In [35]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

# Great Job!
