# NumPy Operations


* 1) Arithmetic and Logic
    - 1.1) Arithmetic
    - 1.2) Logic
* 2) Universal Array Functions
    - 2.1) max, min, average, sum
    - 2.2) power, sqrt, exp, log
    - 2.3) sin, cos, tan
    - 2.4) dot product
* 3) Combine and Split data

## 1) Arithmetic and Logic

You can easily perform array with array arithmetic, or scalar with array arithmetic. <br>
You can also perform logic operation on array. <br>

**Broadcasting**: a technique in numpy used to make operations on different array sizes like multiply or sum a scaler to an array.

Let's see some examples:

### 1.1) Arithmetic

In [1]:
import numpy as np

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
# Also warning, but not an error instead infinity
1 / arr

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [9]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

### 2.2) Logic

In [10]:
arr > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [11]:
arr != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

**We can also do operations on 2-D arrays**

In [12]:
arr = np.random.randint(0,10, (3,3))
arr

array([[7, 2, 2],
       [3, 6, 8],
       [7, 8, 7]])

In [13]:
arr + 3

array([[10,  5,  5],
       [ 6,  9, 11],
       [10, 11, 10]])

In [14]:
arr - 2

array([[5, 0, 0],
       [1, 4, 6],
       [5, 6, 5]])

In [15]:
3 * arr

array([[21,  6,  6],
       [ 9, 18, 24],
       [21, 24, 21]])

In [16]:
arr

array([[7, 2, 2],
       [3, 6, 8],
       [7, 8, 7]])

In [17]:
arr + 3 * arr

array([[28,  8,  8],
       [12, 24, 32],
       [28, 32, 28]])

In [18]:
arr

array([[7, 2, 2],
       [3, 6, 8],
       [7, 8, 7]])

In [19]:
arr * arr

array([[49,  4,  4],
       [ 9, 36, 64],
       [49, 64, 49]])

## 2) Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [20]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
matrix = np.random.randint(0, 100, (5, 3))
matrix

array([[22, 34,  5],
       [74, 23, 49],
       [48, 48,  9],
       [71, 97, 41],
       [ 9, 89, 71]])

### 2.1) max, min, average, sum

**max**

In [22]:
np.max(arr) #same as arr.max()

9

In [23]:
np.max(matrix)

97

In [24]:
np.max(matrix, axis=0)

array([74, 97, 71])

In [25]:
np.max(matrix, axis=1)

array([34, 74, 48, 97, 89])

**min**

In [26]:
np.min(arr) #same as arr.min()

0

In [27]:
np.min(matrix)

5

In [28]:
np.min(matrix, axis=0)

array([ 9, 23,  5])

In [29]:
np.min(matrix, axis=1)

array([ 5, 23,  9, 41,  9])

**average**

In [30]:
np.average(arr)

4.5

In [31]:
np.average(matrix)

46.0

In [32]:
np.average(matrix, axis=0)

array([44.8, 58.2, 35. ])

In [33]:
np.average(matrix, axis=1)

array([20.33333333, 48.66666667, 35.        , 69.66666667, 56.33333333])

**sum**

In [34]:
np.sum(arr)

45

In [35]:
np.sum(matrix)

690

In [36]:
np.sum(matrix, axis=0)

array([224, 291, 175])

In [37]:
np.sum(matrix, axis=1)

array([ 61, 146, 105, 209, 169])

### 2.2) sqrt, exp, log, sin

**power**

In [38]:
np.power(arr, 3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [39]:
np.power(matrix, 3)

array([[ 10648,  39304,    125],
       [405224,  12167, 117649],
       [110592, 110592,    729],
       [357911, 912673,  68921],
       [   729, 704969, 357911]], dtype=int32)

**sqrt**

In [40]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [41]:
np.sqrt(matrix)

array([[4.69041576, 5.83095189, 2.23606798],
       [8.60232527, 4.79583152, 7.        ],
       [6.92820323, 6.92820323, 3.        ],
       [8.42614977, 9.8488578 , 6.40312424],
       [3.        , 9.43398113, 8.42614977]])

**exp**

In [42]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [43]:
np.exp(matrix)

array([[3.58491285e+09, 5.83461743e+14, 1.48413159e+02],
       [1.37338298e+32, 9.74480345e+09, 1.90734657e+21],
       [7.01673591e+20, 7.01673591e+20, 8.10308393e+03],
       [6.83767123e+30, 1.33833472e+42, 6.39843494e+17],
       [8.10308393e+03, 4.48961282e+38, 6.83767123e+30]])

**log**

In [44]:
np.log(arr)

C:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [45]:
np.log(matrix)

array([[3.09104245, 3.52636052, 1.60943791],
       [4.30406509, 3.13549422, 3.8918203 ],
       [3.87120101, 3.87120101, 2.19722458],
       [4.26267988, 4.57471098, 3.71357207],
       [2.19722458, 4.48863637, 4.26267988]])

### 2.3) sin, cos, tan

In [46]:
angels_arr = np.linspace(0, 360, 9).reshape(3, 3)
angels_arr

array([[  0.,  45.,  90.],
       [135., 180., 225.],
       [270., 315., 360.]])

In [47]:
angels_arr = (angels_arr * 2 * np.pi) / 360
angels_arr

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

**sin**

In [48]:
np.sin(angels_arr)

array([[ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 7.07106781e-01,  1.22464680e-16, -7.07106781e-01],
       [-1.00000000e+00, -7.07106781e-01, -2.44929360e-16]])

**cos**

In [49]:
np.cos(angels_arr)

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17],
       [-7.07106781e-01, -1.00000000e+00, -7.07106781e-01],
       [-1.83697020e-16,  7.07106781e-01,  1.00000000e+00]])

**tan**

In [50]:
np.tan(angels_arr)

array([[ 0.00000000e+00,  1.00000000e+00,  1.63312394e+16],
       [-1.00000000e+00, -1.22464680e-16,  1.00000000e+00],
       [ 5.44374645e+15, -1.00000000e+00, -2.44929360e-16]])

### 2.4) dot product

In [51]:
mat = np.arange(9).reshape(3,3)
vec1 = np.array([1,2,3])

print(mat)
print()
print(vec1)
print()
print(np.dot(vec1, mat))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[1 2 3]

[24 30 36]


In [52]:
vec1.dot(mat)

array([24, 30, 36])

## 3) Combine and Split data

* hstack
* vstack
* concatenate
* hsplit
* vsplit

### hstack

In [53]:
data1 = np.random.randint(5,15,size=(5,3))
data1

array([[ 9,  8, 12],
       [13, 12, 11],
       [ 5,  8, 14],
       [14,  5,  8],
       [14,  7, 13]])

In [54]:
data2 = np.random.randint(5,15,size=(5,3))
data2

array([[11, 10,  5],
       [ 5,  7,  8],
       [ 5,  6,  7],
       [ 5, 13,  5],
       [ 9,  8, 11]])

In [55]:
np.hstack([data1,data2])

array([[ 9,  8, 12, 11, 10,  5],
       [13, 12, 11,  5,  7,  8],
       [ 5,  8, 14,  5,  6,  7],
       [14,  5,  8,  5, 13,  5],
       [14,  7, 13,  9,  8, 11]])

### vstack

In [56]:
np.vstack([data1,data2])

array([[ 9,  8, 12],
       [13, 12, 11],
       [ 5,  8, 14],
       [14,  5,  8],
       [14,  7, 13],
       [11, 10,  5],
       [ 5,  7,  8],
       [ 5,  6,  7],
       [ 5, 13,  5],
       [ 9,  8, 11]])

### concatenate

In [57]:
# stack vertical rows
np.concatenate([data1, data2], axis=0)

array([[ 9,  8, 12],
       [13, 12, 11],
       [ 5,  8, 14],
       [14,  5,  8],
       [14,  7, 13],
       [11, 10,  5],
       [ 5,  7,  8],
       [ 5,  6,  7],
       [ 5, 13,  5],
       [ 9,  8, 11]])

In [58]:
# stack horizontal columns
np.concatenate([data1, data2], axis=1)

array([[ 9,  8, 12, 11, 10,  5],
       [13, 12, 11,  5,  7,  8],
       [ 5,  8, 14,  5,  6,  7],
       [14,  5,  8,  5, 13,  5],
       [14,  7, 13,  9,  8, 11]])

### hsplit

In [59]:
stacked_data = np.hstack([data1,data2])
stacked_data

array([[ 9,  8, 12, 11, 10,  5],
       [13, 12, 11,  5,  7,  8],
       [ 5,  8, 14,  5,  6,  7],
       [14,  5,  8,  5, 13,  5],
       [14,  7, 13,  9,  8, 11]])

In [60]:
left, right = np.hsplit(stacked_data, 2)

In [61]:
left

array([[ 9,  8, 12],
       [13, 12, 11],
       [ 5,  8, 14],
       [14,  5,  8],
       [14,  7, 13]])

In [62]:
right

array([[11, 10,  5],
       [ 5,  7,  8],
       [ 5,  6,  7],
       [ 5, 13,  5],
       [ 9,  8, 11]])

### vsplit

In [63]:
stacked_data = np.vstack([data1,data2])
stacked_data

array([[ 9,  8, 12],
       [13, 12, 11],
       [ 5,  8, 14],
       [14,  5,  8],
       [14,  7, 13],
       [11, 10,  5],
       [ 5,  7,  8],
       [ 5,  6,  7],
       [ 5, 13,  5],
       [ 9,  8, 11]])

In [64]:
up, down = np.vsplit(stacked_data, 2)

In [65]:
up

array([[ 9,  8, 12],
       [13, 12, 11],
       [ 5,  8, 14],
       [14,  5,  8],
       [14,  7, 13]])

In [66]:
down

array([[11, 10,  5],
       [ 5,  7,  8],
       [ 5,  6,  7],
       [ 5, 13,  5],
       [ 9,  8, 11]])

# Great Job!

That's all we need to know for now!