In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
num_episodes = 10000
# num_episodes = 50000
max_steps_per_episode = 100

learning_rate = 0.8
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [4]:
rewards_all_episodes = []

In [9]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
#         env.render()
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        # Set new state
        state = new_state
        rewards_current_episode += reward 
        
        if done:
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)

In [10]:
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.8360000000000006
2000 :  0.9500000000000007
3000 :  1.0020000000000004
4000 :  1.0030000000000003
5000 :  0.9690000000000007
6000 :  0.8000000000000006
7000 :  0.9630000000000007
8000 :  0.9900000000000008
9000 :  0.9930000000000008
10000 :  0.8630000000000007


In [11]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[6.76757556e-01 3.73808061e-01 3.41787261e-01 1.56198610e-01]
 [3.38564493e-02 6.40361053e-02 2.26991465e-02 5.58145405e-01]
 [2.92455472e-02 1.12978785e-01 2.36132929e-02 4.68630382e-01]
 [3.48501181e-02 4.01300413e-02 2.38831670e-02 2.85047714e-01]
 [7.02120162e-01 1.25057134e-02 1.68346010e-01 7.37768189e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.34600422e-02 1.21719587e-05 5.93352412e-06 8.19942474e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.46988458e-03 1.65363318e-02 2.65853153e-02 7.08724060e-01]
 [4.48129907e-03 8.74803543e-01 2.73453225e-02 1.36448125e-03]
 [9.64564044e-01 1.46519944e-03 3.09921012e-03 4.58624983e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.26226315e-01 1.32661780e-01 8.96330894e-01 1.61079057e-01]
 [3.50087901e-01 9.97430189e-01 2.61892565e-01 2.16900905e-01]
 [0.00000000e+00 0.00000000e

In [12]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = new_state
        env.render()
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
****You fell through a hole!****
