# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.


* 1) Indexing
    - 1.1) Indexing 1D array (Vectors)
    - 1.2) Indexing 2D array (Matrices)
    - 1.3) Fancy Indexing
* 2) Selection

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(30,40)

In [3]:
#Show
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

## 1) Indexing
The simplest way to pick one or some elements of an array looks very similar to python lists:

### 1.1) Indexing a 1D array (Vectors)

In [4]:
#Get a value at an index
arr[8]

38

In [5]:
#Get values in a range
arr[1:5]

array([31, 32, 33, 34])

In [6]:
#Get values in a range
arr[0:5]

array([30, 31, 32, 33, 34])

In [7]:
arr[:5]

array([30, 31, 32, 33, 34])

In [8]:
arr[3:]

array([33, 34, 35, 36, 37, 38, 39])

In [9]:
arr[3:7]

array([33, 34, 35, 36])

In [10]:
arr[3:7:2]

array([33, 35])

**if you want to make operation on a copy of the array and don't change the base array just use .copy()**


In [11]:
arr = np.arange(30,40)
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [12]:
#Setting a value with index range (Broadcasting)
arr[0:5] = 100

#Show
arr

array([100, 100, 100, 100, 100,  35,  36,  37,  38,  39])

In [13]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(30,40)

#Show
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [14]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([30, 31, 32, 33, 34, 35])

In [15]:
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [16]:
arr

array([99, 99, 99, 99, 99, 99, 36, 37, 38, 39])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [17]:
myarr = np.arange(30,40)
myarr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [18]:
arr = myarr.copy()
arr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [19]:
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([30, 31, 32, 33, 34, 35])

In [20]:
slice_of_arr[:] = 99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99, 99, 36, 37, 38, 39])

In [22]:
myarr

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

### 1.2) Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [25]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [26]:
# Getting individual element value
arr_2d[1,0]

20

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [29]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [30]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [31]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [32]:
arr_2d[::-1,::]

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

In [33]:
arr_2d[:,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [34]:
arr_2d[::-1,::-1]

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

### 1.3) Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [35]:
#Set up matrix
arr2d = np.zeros((10,10))

In [36]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
for i in range(10):
    arr2d[i] = i + 2
    
arr2d

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11.]])

Fancy indexing allows the following

In [38]:
arr2d[[1,4,6,8]]

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [39]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [40]:
arr2d[[1,4,6,8], 2:5]

array([[ 3.,  3.,  3.],
       [ 6.,  6.,  6.],
       [ 8.,  8.,  8.],
       [10., 10., 10.]])

## 2) Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [41]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True])

In [43]:
bool_arr = arr > 4

In [44]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True])

In [45]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [46]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[arr >= 5]

array([5, 6, 7, 8, 9])

In [48]:
x = 3
arr[arr > x]

array([4, 5, 6, 7, 8, 9])

In [49]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[arr % 2 == 0]

array([2, 4, 6, 8])

# Great Job!
